<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EthersyncGeneratedDir Condition="'$(EthersyncGeneratedDir)' == ''">$(MSBuildThisFileDirectory)../../target/debug/ethersync-generated/native</EthersyncGeneratedDir>
    <EthersyncNativeLibraryDir Condition="'$(EthersyncNativeLibraryDir)' == ''">$(MSBuildThisFileDirectory)../../target/debug</EthersyncNativeLibraryDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(EthersyncGeneratedDir)/NativeMethods.g.cs" />
    <Compile Include="$(EthersyncGeneratedDir)/Ethersync.g.cs" />
    <Compile Include="$(EthersyncGeneratedDir)/Ethersync.Support.cs" />
    <Compile Include="$(EthersyncGeneratedDir)/Ethersync.Native.cs" Condition="Exists('$(EthersyncGeneratedDir)/Ethersync.Native.cs')" />
    <None Include="$(EthersyncNativeLibraryDir)/libethersync_bindings.dylib" Condition="Exists('$(EthersyncNativeLibraryDir)/libethersync_bindings.dylib')" Link="libethersync_bindings.dylib" CopyToOutputDirectory="Always" CopyToPublishDirectory="PreserveNewest" />
    <None Include="$(EthersyncNativeLibraryDir)/libethersync_bindings.so" Condition="Exists('$(EthersyncNativeLibraryDir)/libethersync_bindings.so')" Link="libethersync_bindings.so" CopyToOutputDirectory="Always" CopyToPublishDirectory="PreserveNewest" />
    <None Include="$(EthersyncNativeLibraryDir)/ethersync_bindings.dll" Condition="Exists('$(EthersyncNativeLibraryDir)/ethersync_bindings.dll')" Link="ethersync_bindings.dll" CopyToOutputDirectory="Always" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
