[workspace]
members = ["protocol", "native", "clients/wasm", "clients/bindings", "clients/sdk"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
prost = "0.14.4"
thiserror = "2.0.20"
moq-core = { package = "moq-net", git = "https://github.com/moq-dev/moq", rev = "5d0991b9991305be907e6c0682a4e276722eeed0" }
