[package]
name = "ethersync"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ethersync-transport = { path = "../transport" }
mio = { version = "1", features = ["net", "os-poll"] }
web-transport-trait = "0.4"
ethersync-protocol = { path = "../protocol", version = "0.1.0" }
thiserror.workspace = true
mdns-sd = "0.21.3"
triple_buffer = "9.0.0"
uuid = { version = "1.26.1", features = ["v4"] }

[[example]]
name = "leader"
path = "../examples/leader.rs"
[[example]]
name = "follower"
path = "../examples/follower.rs"
[[example]]
name = "tracked"
path = "../examples/tracked.rs"

[dev-dependencies]
moq-net = "0.2.22"
moq-native = { version = "0.19.19", default-features = false, features = ["quinn", "ring"] }
tokio = { version = "1.53.1", features = ["rt", "sync", "time", "macros", "net"] }
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }
crossterm = "0.29.0"
