<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DefineConstants Condition="'$(TidkodCoreOnly)' != 'true'">$(DefineConstants);TIDKOD_NATIVE</DefineConstants>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../Tidkod.csproj" /></ItemGroup>
</Project>
